---
- name: 'Configure and start Docker Engine'
  become: true
  block:
    - name: 'Ensure Docker Engine is running and enabled at boot'
      ansible.builtin.systemd:
        name: 'docker'
        state: 'started'
        enabled: true
      when: not ansible_check_mode

    - name: 'Configure Docker Engine daemon'
      ansible.builtin.copy:
        content: '{{ docker_daemon_options | to_nice_json }}'
        dest: '/etc/docker/daemon.json'
        owner: 'root'
        group: 'root'
        mode: 0644
      notify: 'Restart Docker'
      when: docker_daemon_options.keys() | length

    - name: 'Ensure docker users are added to the docker group'
      ansible.builtin.user:
        name: '{{ docker_user }}'
        groups: 'docker'
        append: true
      loop: '{{ docker_users }}'
      loop_control:
        loop_var: docker_user
