---
- name: 'Post-installation tasks for Docker Engine'
  become: true
  block:
    - name: 'Ensure Docker Engine is running and enabled at boot'
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: 'Ensure docker users are added to the docker group'
      user:
        name: '{{ _docker_user }}'
        groups: docker
        append: true
      loop: '{{ docker_users }}'
      loop_control:
        loop_var: _docker_user
