---
- name: 'Debian | Configure the repository and install the Docker Engine packages'
  become: true
  block:
    - name: 'Debian | Remove the conflicting Docker Engine packages'
      ansible.builtin.apt:
        name:
          - 'containerd'
          - 'docker.io'
          - 'docker-compose'
          - 'docker-doc'
          - 'podman-docker'
          - 'runc'
        state: 'absent'

    - name: 'Debian | Ensure the dependencies are installed'
      ansible.builtin.apt:
        name:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'gnupg'
        update_cache: true
        cache_valid_time: 3600
        state: 'present'
      check_mode: false

    - name: 'Debian | Add the Docker Engine repository GPG key'
      ansible.builtin.apt_key:
        url: '{{ docker_repository_gpgkey_url }}'
        keyring: '{{ __docker_repository_gpgkey_keyring }}'
        state: 'present'

    - name: 'Debian | Add the Docker Engine repository'
      ansible.builtin.template:
        src: 'docker.list.j2'
        dest: '/etc/apt/sources.list.d/docker.list'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Debian | Install the Docker Engine packages'
      ansible.builtin.apt:
        name:
          - 'containerd.io'
          - "docker-ce{{ ('=' + docker_package_version) if (docker_package_version | length) else '' }}"
          - "docker-ce-cli{{ ('=' + docker_package_version) if (docker_package_version | length) else '' }}"
          - 'docker-buildx-plugin'
          - 'docker-compose-plugin'
        allow_downgrade: true
        update_cache: true
        state: "{{ 'present' if (docker_package_version | length) else 'latest' }}"
      ignore_errors: '{{ ansible_check_mode }}'
