---
- name: 'RedHat | Configure the repository and install the Docker Engine packages'
  become: true
  block:
    - name: 'RedHat | Remove the conflicting Docker Engine packages'
      ansible.builtin.yum:
        name: '{{ __docker_conflicting_packages }}'
        autoremove: true
        state: 'absent'

    - name: 'RedHat | Ensure the dependencies are installed'
      ansible.builtin.package:
        name:
          - 'ca-certificates'
          - 'yum-utils'
        state: 'present'

    - name: 'RedHat | Add the Docker Engine repository'
      ansible.builtin.template:
        src: 'docker.repo.j2'
        dest: '/etc/yum.repos.d/docker.repo'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'RedHat | Install the Docker Engine packages'
      ansible.builtin.yum:
        name: '{{ __docker_packages }}'
        allow_downgrade: true
        update_cache: true
        state: "{{ (docker_setup == 'upgrade') | ternary('latest', 'present') }}"
      ignore_errors: '{{ ansible_check_mode }}'
