---
- name: 'Configure YUM/DNF repository and install Docker Engine package'
  become: true
  block:
    - name: 'Ensure dependencies are installed'
      ansible.builtin.package:
        name: yum-utils
        state: present

    - name: 'Add Docker Engine DNF/YUM repository'
      ansible.builtin.template:
        src: 'docker.repo.j2'
        dest: '/etc/yum.repos.d/docker.repo'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Install Docker Engine packages'
      ansible.builtin.dnf:
        name:
          - "docker-ce{{ ('-' + docker_version) if (docker_version | length) else '' }}"
          - "docker-ce-cli{{ ('-' + docker_version) if (docker_version | length) else '' }}"
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        allow_downgrade: "{{ omit if ansible_version['full'] is version('2.12', '<') else true }}"
        update_cache: true
        state: "{{ 'present' if (docker_version | length) else 'latest' }}"
