---
- name: 'Configure APT repository and install Docker Engine packages'
  become: true
  block:
    - name: 'Ensure dependencies are installed'
      ansible.builtin.apt:
        name:
          - ca-certificates
          - gnupg
        update_cache: true
        state: present

    - name: 'Add Docker Engine APT key'
      ansible.builtin.apt_key:
        url: '{{ _docker_apt_repository_gpgkey }}'
        keyring: '{{ _docker_apt_local_gpgkey }}'
        state: present
      when: not ansible_check_mode

    - name: 'Add Docker repository APT key'
      ansible.builtin.template:
        src: 'docker.list.j2'
        dest: '/etc/apt/sources.list.d/docker.list'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Install Docker Engine packages'
      ansible.builtin.apt:
        name:
          - "docker-ce{{ ('=' + docker_version) if (docker_version | length) else '' }}"
          - "docker-ce-cli{{ ('=' + docker_version) if (docker_version | length) else '' }}"
          - docker-buildx-plugin
          - docker-compose-plugin
        allow_downgrade: "{{ omit if ansible_version['full'] is version('2.12', '<') else true }}"
        update_cache: true
        state: "{{ 'present' if (docker_version | length) else 'latest' }}"
