---
- name: 'RedHat | Configure the repository and install the Docker Engine packages'
  become: true
  block:
    - name: 'RedHat | Remove the conflicting Docker Engine packages'
      ansible.builtin.yum:
        name:
          - 'docker'
          - 'docker-client'
          - 'docker-client-latest'
          - 'docker-common'
          - 'docker-engine'
          - 'docker-engine-selinux.noarch'
          - 'docker-latest'
          - 'docker-latest-logrotate'
          - 'docker-logrotate'
          - 'docker-selinux.noarch'
          - 'podman'
          - 'runc'
        autoremove: true
        state: 'absent'

    - name: 'RedHat | Ensure the dependencies are installed'
      ansible.builtin.package:
        name:
          - 'ca-certificates'
          - 'yum-utils'
        state: 'present'

    - name: 'RedHat | Add the Docker Engine repository'
      ansible.builtin.template:
        src: 'docker.repo.j2'
        dest: '/etc/yum.repos.d/docker.repo'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'RedHat | Install the Docker Engine packages'
      ansible.builtin.yum:
        name:
          - 'containerd.io'
          - "docker-ce{{ ('-' + docker_package_version) if (docker_package_version | length) else '' }}"
          - "docker-ce-cli{{ ('-' + docker_package_version) if (docker_package_version | length) else '' }}"
          - 'docker-buildx-plugin'
          - 'docker-compose-plugin'
        allow_downgrade: true
        update_cache: true
        state: "{{ (docker_setup == 'upgrade') | ternary('latest', 'present') }}"
      ignore_errors: '{{ ansible_check_mode }}'
