---
- name: 'Install Docker Engine'
  ansible.builtin.include_tasks: "install-{{ ansible_facts['os_family'] }}.yml"
  when: docker_setup in ['install', 'upgrade']

- name: 'Configure Docker Engine'
  ansible.builtin.include_tasks: 'configure.yml'
  when: docker_setup in ['install', 'upgrade']

- name: 'Uninstall Docker Engine'
  ansible.builtin.include_tasks: 'uninstall.yml'
  when: docker_setup in ['uninstall']
