---
- name: 'Load the Docker Engine OS-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Install Docker Engine'
  ansible.builtin.include_tasks: 'install-{{ ansible_os_family }}.yml'

- name: 'Configure Docker Engine'
  ansible.builtin.import_tasks: 'configure.yml'
