---
- name: 'Include the Docker Engine OS-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Include tasks to install Docker Engine'
  ansible.builtin.include_tasks: 'install-{{ ansible_os_family }}.yml'

- name: 'Include tasks to configure Docker Engine'
  ansible.builtin.import_tasks: 'configure.yml'
