---
- name: 'Install Docker Engine'
  ansible.builtin.include_tasks: 'install-{{ ansible_os_family }}.yml'
  when: docker_setup in ['install','upgrade']

- name: 'Configure Docker Engine'
  ansible.builtin.import_tasks: 'configure.yml'
  when: docker_setup in ['install','upgrade']
