---
- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Gathering Service Facts'
      ansible.builtin.service_facts:

    - name: 'Assert that docker service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker.service'].state == 'running' or
            ansible_facts.services['docker.service'].state == 'active'
          - ansible_facts.services['docker.service'].status == 'enabled' or
            ansible_facts.services['docker.service'].status == 'enabled'

    - name: 'Check current Docker Engine version'
      ansible.builtin.command:
        cmd: '/usr/bin/docker --version'
      changed_when: false
      register: _docker_version_check

    - name: 'Version output'
      ansible.builtin.debug:
        var: _docker_version_check.stdout_lines[0]
