---
- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Gathering Service Facts'
      ansible.builtin.service_facts:

    - name: 'Assert that Docker Engine service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker.service'].state == 'running' or
            ansible_facts.services['docker.service'].state == 'active'
          - ansible_facts.services['docker.service'].status == 'enabled'

    - name: 'Assert that Containerd service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['containerd.service'].state == 'running' or
            ansible_facts.services['containerd.service'].state == 'active'
          - ansible_facts.services['containerd.service'].status == 'enabled'

    - name: 'Check the current Docker Engine version'
      ansible.builtin.command:
        cmd: '/usr/bin/docker --version'
      changed_when: false
      register: __docker_version_check

    - name: 'The Docker Engine version output'
      ansible.builtin.debug:
        msg: 'The current Docker Engine version is {{ __docker_version_check.stdout_lines[0].split()[2] }}'

    - name: 'Run hello-world container'
      ansible.builtin.command:
        cmd: 'docker run --rm hello-world'
      changed_when: false
      register: __hello_world

    - name: 'Hello world output'
      ansible.builtin.debug:
        var: __hello_world.stdout_lines
